run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - exportloopref
    - gocheckcompilerdirectives
    # FIXME: for some reason this errors on windows
    # - gofmt
    # - goimports
    # TODO: disable for now
    # - intrange
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - testifylint
    - unconvert
    - unused
    # TODO: bmizerany says no :(
    # - usestdlibvars
    - wastedassign
    - whitespace
